import org.opencv.core.Mat;

/**
 * Created by William Kluge on 1/17/17.
 * This is an interface to specify what is needed for @see TableHandler to be able to use a GRIP pipeline
 * T should either be ArrayList<Line> (if using findLines or filterLines), MatOfKeyPoint (if using blobs), or
 * ArrayList<MatOfPoint> (if using findContours or filterContours)
 * @apiNote You need to implement this in whatever pipeline you're using
 */
public interface PipelineInterface<T> {

    /**
     * This is the method to actually do the processing of the pipeline. This will be auto-generated by GRIP.
     * @param source0 The source image to process
     */
    void process(Mat source0);

    /**
     * This method allows for TableHandler to deal with data specific to your type of output, while still remaining in
     * one general interface.
     * @apiNote You will need to make this function in the generated GRIP file!
     * @return The final output of your generated GRIP filter
     */
    T contentOutput();

}
