import edu.wpi.first.wpilibj.networktables.NetworkTable;
import org.opencv.core.Mat;
import org.opencv.videoio.VideoCapture;

/**
 * Created by William Kluge on 1/17/17.
 * This class is used to handle the NetworkTable and send data to the roboRIO from a GRIP pipeline dealing with
 * contours.
 * T should be the vision pipeline generated by GRIP
 */
public class TableHandler<T extends PipelineInterface> {

    /* The network table to use for this vision system */
    private NetworkTable networkTable;
    /* VideoCapture for image processing */
    private VideoCapture videoCapture;
    /* The GRIP pipeline that contains the OpenCV filtering */
    private T gripPipeline;

    /**
     * Constructs the TableHandler class
     * @param tableName The name of the table to output to
     * @param deviceID The ID of the device for this to look for
     */
    TableHandler(String tableName, int deviceID) {
        networkTable = NetworkTable.getTable(tableName);
        videoCapture = new VideoCapture(deviceID);
    }

    /**
     * Updates the network table with the most recent data
     */
    public synchronized void updateTable() {
        Mat frame = new Mat();
        videoCapture.grab();
        videoCapture.retrieve(frame);
        gripPipeline.process(frame);
        Object o = gripPipeline.contentOutput();
    }

}
